/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/price/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current canonical price
         * @description Returns the latest canonical BTC/USD price from memory (lowest latency)
         */
        get: operations["getLatestPrice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/price/settlement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get settlement price
         * @description Returns the official settlement price at a specific 5-minute boundary.
         *     **Primary endpoint for prediction market resolution.**
         */
        get: operations["getSettlementPrice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/price/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query historical snapshots
         * @description Returns 1-second snapshots in a time range
         */
        get: operations["getSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/price/ticks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query recent price ticks
         * @description Returns recent canonical price change events
         */
        get: operations["getTicks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/price/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query raw exchange data
         * @description Returns raw tick data from individual exchanges (for auditing)
         */
        get: operations["getRawTicks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-source feed health */
        get: operations["getFeedHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LatestPrice: {
            /** @example BTC/USD */
            symbol: string;
            /**
             * Format: date-time
             * @description Timestamp of the price event
             */
            ts: string;
            /**
             * @description Canonical price (decimal string)
             * @example 70105.45
             */
            price: string;
            /**
             * @description How the price was computed
             * @enum {string}
             */
            basis: "median_trade" | "median_mixed" | "single_trade" | "single_midpoint" | "carry_forward";
            /** @description True if data is outdated */
            is_stale?: boolean;
            /** @description True if fewer than minimum sources */
            is_degraded?: boolean;
            /**
             * Format: float
             * @description Data quality metric
             */
            quality_score?: number;
            /** @description Number of sources used */
            source_count: number;
            /**
             * @example [
             *       "binance",
             *       "coinbase",
             *       "kraken"
             *     ]
             */
            sources_used?: string[];
        };
        SettlementPrice: {
            /**
             * Format: date-time
             * @description The settlement timestamp (5-minute boundary)
             */
            settlement_ts: string;
            /** @example BTC/USD */
            symbol: string;
            /**
             * @description Official settlement price
             * @example 70105.45
             */
            price: string;
            /**
             * @description - confirmed: High quality, safe for auto-settlement
             *     - degraded: Fewer sources, use with caution
             *     - stale: No fresh data, manual review recommended
             * @enum {string}
             */
            status: "confirmed" | "degraded" | "stale";
            /** @enum {string} */
            basis: "median_trade" | "median_mixed" | "single_trade" | "single_midpoint" | "carry_forward";
            /** Format: float */
            quality_score?: number;
            source_count?: number;
            sources_used?: string[];
            /**
             * Format: date-time
             * @description When the snapshot was finalized
             */
            finalized_at?: string;
            /**
             * Format: byte
             * @description Base64-encoded JSON with per-source details (for audit)
             */
            source_details?: string;
        };
        Snapshot: {
            /** Format: date-time */
            ts_second?: string;
            symbol?: string;
            price?: string;
            basis?: string;
            is_stale?: boolean;
            is_degraded?: boolean;
            quality_score?: number;
            source_count?: number;
            sources_used?: string[];
            /** Format: date-time */
            finalized_at?: string;
        };
        Tick: {
            /** Format: date-time */
            ts?: string;
            symbol?: string;
            price?: string;
            basis?: string;
            is_stale?: boolean;
            is_degraded?: boolean;
            quality_score?: number;
            source_count?: number;
            sources_used?: string[];
        };
        RawEvent: {
            /** Format: uuid */
            event_id?: string;
            /** @enum {string} */
            source?: "binance" | "coinbase" | "kraken" | "okx";
            /** @enum {string} */
            event_type?: "trade" | "ticker";
            /** Format: date-time */
            exchange_ts?: string;
            /** Format: date-time */
            recv_ts?: string;
            price?: string;
            size?: string;
            /** @enum {string} */
            side?: "buy" | "sell";
            trade_id?: string;
        };
        Health: {
            /** @enum {string} */
            status?: "ok" | "degraded" | "stale" | "no_data";
            /** Format: date-time */
            timestamp?: string;
            latest_price?: string;
            /** Format: date-time */
            latest_ts?: string;
            source_count?: number;
        };
        FeedHealth: {
            source?: string;
            /** @enum {string} */
            conn_state?: "connected" | "connecting" | "disconnected";
            /** Format: date-time */
            last_message_ts?: string;
            /** Format: date-time */
            last_trade_ts?: string;
            median_lag_ms?: number;
            reconnect_count_1h?: number;
            consecutive_errors?: number;
            stale?: boolean;
            /** Format: date-time */
            updated_at?: string;
        };
        Error: {
            /** @description Error message */
            error: string;
        };
        /**
         * @description Base schema for all WebSocket messages. The `type` field determines which
         *     additional fields are present.
         */
        WSMessage: {
            /**
             * @description Message type
             * @enum {string}
             */
            type: "welcome" | "latest_price" | "snapshot_1s" | "heartbeat";
            /**
             * Format: uint64
             * @description Monotonically increasing sequence number. Present on all broadcast
             *     messages (latest_price, snapshot_1s, heartbeat). Absent on per-connection
             *     messages (welcome, initial_state). Clients detect gaps to know when
             *     messages were missed.
             */
            seq?: number;
            /**
             * Format: date-time
             * @description Timestamp of the event or server time
             */
            ts: string;
            /** @description Canonical price (decimal string). Present on latest_price and snapshot_1s. */
            price?: string;
            /** @enum {string} */
            basis?: "median_trade" | "median_mixed" | "single_trade" | "single_midpoint" | "carry_forward";
            is_stale?: boolean;
            /** @description Quality metric as decimal string */
            quality_score?: string;
            source_count?: number;
            sources_used?: string[];
            /**
             * @description Context for special messages:
             *     - `"btick/v1"` on welcome
             *     - `"initial_state"` on first latest_price after connect
             *     - `"no_data_yet"` if no price data available on connect
             */
            message?: string;
        };
        /**
         * @description Client-to-server message for subscription management.
         *     Unknown actions and types are silently ignored (forward-compatible).
         */
        WSClientAction: {
            /**
             * @description Subscribe or unsubscribe from message types
             * @enum {string}
             */
            action: "subscribe" | "unsubscribe";
            /** @description Message types to subscribe/unsubscribe */
            types: ("snapshot_1s" | "latest_price" | "heartbeat")[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLatestPrice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current price */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestPrice"];
                };
            };
            /** @description No data available yet */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSettlementPrice: {
        parameters: {
            query: {
                /**
                 * @description Settlement timestamp (RFC3339). Must be on a 5-minute boundary.
                 * @example 2026-03-19T09:10:00Z
                 */
                ts: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settlement price */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettlementPrice"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No data for timestamp */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Price not yet finalized */
            425: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSnapshots: {
        parameters: {
            query: {
                /** @description Start time (RFC3339) */
                start: string;
                /** @description End time (RFC3339), defaults to now */
                end?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of snapshots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"][];
                };
            };
        };
    };
    getTicks: {
        parameters: {
            query?: {
                /** @description Number of ticks to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of ticks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tick"][];
                };
            };
        };
    };
    getRawTicks: {
        parameters: {
            query?: {
                /** @description Filter by source */
                source?: "binance" | "coinbase" | "kraken" | "okx";
                start?: string;
                end?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of raw events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawEvent"][];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getFeedHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feed health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedHealth"][];
                };
            };
        };
    };
}
